### PR TITLE
Update the description of the "Data" tag

### PR DESCRIPTION
**Pull request by iherman**

### CODE REVIEW

**Comment by iherman** [comment]
Relevant to #56

**Comment by deniak** [comment]
:-1: on having 2 tags with the same meaning. We should keep one only and stick to it. I think `Data` has a more general meaning and may suit more specs.

**Comment by iherman** [comment]
Will those descriptions also appear somewhere? If so, I am fine keeping the 'Data' tag only, but with an updated definition.

**Comment by deniak** [comment]
I'm not sure yet where @koalie and @plehegar prefer to have that list (GH or somewhere else) but the goal is to point people to it as a reference so they know what they can find behind each tag.

**Comment by iherman** [comment]
@deniak I have kept the "Data" tag only with the new definition (just committed).

**Comment by plehegar** [comment]
@iherman , by saying "semantically rich", would that exclude any JSON only format/protocol? (in contrast to JSON-LD for example) ?

**Comment by plehegar** [comment]
and yes, our goal is to keep the official tag list as small as possible, to avoid cluttering the UI. We could have a secondary set of tags that wouldn't appear in the UI in the future.

**Comment by plehegar** [comment]
regarding where we're hosting the list, we could have a copy on w3.org if needed, but the maintenance of the list should be kept in this repository to facilitate discussions.

**Comment by iherman** [comment]
> @iherman , by saying "semantically rich", would that exclude any JSON only format/protocol? (in contrast to JSON-LD for example) ?

Hm, good question, @plehegar. It may not be a stretch, however, to say that if we defined some sort of a data format based on JSON, that would mean defining the keys, ie, attach some sort of a semantics to those. I realize the borderlines are fuzzy, but I guess we are not trying to create mathematically clean definitions, and WG-s should always have the last word whether a specific technology falls into this category or not…

**Comment by tripu** [comment]
@koalie, I can rebase & merge this PR, if you're OK with it, too.

**Pull request merged**
