### PR TITLE
a few small changes to improve readability

### PR DESCRIPTION
**Pull request by gosko**
Hi, the mockup-rwd design is looking pretty good, nice work!

I find it a little bit difficult to read, maybe because there are so many font styles? I did some experimenting with the style, please let me know what you think.

screen shot 2018-03-08 at 6 00 32 pm

I made a few small changes to the HTML as well as the CSS:

  - replaced "Published on" with a class name
  - removed emphasis from "Editor's Draft", and moved that to the same line as "History"
  - added an \&nbsp; between words in 'Level 1', to avoid the 1 getting wrapped onto a line of its own (maybe there is a smarter way to do this using CSS instead of \&nbsp;)

### CODE REVIEW

**Comment by tripu** [comment]
@gosko: care to rebase your branch, to better examine the diff (`mockup1/index.html` has lots of changes)? Or I can do that myself; there are no conflicts, so it's immediate.

**Comment by tripu** [comment]
Thanks!

**Comment by gosko** [comment]
@tripu sure, done (I hope!)

**Comment by tripu** [comment]
@deniak, these changes look good to me.

* The first two require small changes on your side. Are you okay with those?
* The 3<sup>rd</sup> is low-priority, I think, and it also has to be implemented server-side. It can wait, as we agreed.

Some of these changes clash with my own in #50; but since this PR was first, I'll take care of merging @gosko's changes with mine.

**Comment by deniak** [comment]
Thanks @gosko! @tripu feel free to rebase onto `master`.

**Comment by deniak** [comment]
Ok, it'll all integrated and will be deployed soon. I think I managed to add the `&nbsp;` too when it's necessary.

**Comment by gosko** [comment]
Hi again @deniak @tripu, I just saw the new version on https://www.w3.org/TR/ and noticed it is missing a few of the changes I suggested; was that deliberate or an oversight?

screen shot 2018-03-20 at 12 30 14 pm

In particular, I am not a fan of the large font and small line-height used in the spec titles. Also I prefer a less bold font and less padding in the spec maturity labels, but that is fairly minor.

If there is a better way to contribute patches just let me know :)

**Comment by deniak** [comment]
@gosko yes, we deployed the new version yesterday but there are more "minor" updates coming up. Regarding the changes you suggested, I'm not sure about their status. https://github.com/w3c/tr-pages/pull/50 was conflicting with it so maybe some rules in the CSS were missed during the rebase. @tripu should be able to answer.

About the font size of the title, I agree with you. It looks quite big compared to the rest of the details. @tripu @tanyeah WDYT?

**Comment by tripu** [comment]
@gosko, @deniak: Yes, #50 changed the markup a bit (and its classes); I had to solve some conflicts when rebasing to be able to merge. Some of @gosko's changes were made obsolete by my own, but I may have broken others inadvertently :confused:

So, part deliberate, part oversight&hellip;

@gosko, issues and PRs here is the right way! Thank you! Don't give up on us! :)

I'm OK reducing the font size and weight of spec titles, and increasing the line height.

I think I'll submit a new PR with those changes, plus some of what @gosko suggested here: https://github.com/w3c/tr-pages/issues/44#issuecomment-374737421&hellip;

**Pull request merged**
